# ============ MYSQL DEPLOYMENT ============
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Thu ha123"
        - name: MYSQL_DATABASE
          value: "week2"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mysqladmin ping -h 127.0.0.1 -uroot -p"Thu ha123"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mysqladmin ping -h 127.0.0.1 -uroot -p"Thu ha123"
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mysql-storage
        emptyDir: {}

# ============ MYSQL SERVICE ============
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP


# # ============ MYSQL DEPLOYMENT ============
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql:8.0
#         ports:
#         - containerPort: 3306
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           value: "Thu ha123"
#         - name: MYSQL_DATABASE
#           value: "week2"
#         volumeMounts:
#         - name: mysql-storage
#           mountPath: /var/lib/mysql
#         livenessProbe:
#           exec:
#             command:
#             - /bin/sh
#             - -c
#             - mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD
#           initialDelaySeconds: 30
#           periodSeconds: 10
#         readinessProbe:
#           exec:
#             command:
#             - /bin/sh
#             - -c
#             - mysqladmin ping -h localhost -uroot -p"${MYSQL_ROOT_PASSWORD}"
#           initialDelaySeconds: 10
#           periodSeconds: 5
#       volumes:
#       - name: mysql-storage
#         persistentVolumeClaim:
#           claimName: mysql-pvc
