version: "3.8"

services:
  app:
    build: .
    container_name: my-java-app
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/week2
      #Spring Boot container sẽ truy cập MySQL container bằng tên service mysql-db, không phải localhost.
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "Thu ha123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # SPRING_JPA_SHOW_SQL: "true"
      # SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Thu ha123"
      MYSQL_DATABASE: week2
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pThu ha123"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  my-network:
